export const GET_FOLLOWERS_LIST = 'GET_FOLLOWERS_LIST';
export const GET_FOLLOWING_LIST = 'GET_FOLLOWING_LIST';
export const UP_STATUS = 'UP_STATUS';
export const GET_USER_LIST = 'GET_USER_LIST';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const UPDATE_PROFILE_INFO = 'UPDATE_PROFILE_INFO'