export const GET_FOLLOWERS_LIST = 'GET_FOLLOWERS_LIST';
export const GET_FOLLOWING_LIST = 'GET_FOLLOWING_LIST';
export const UP_STATUS = 'UP_STATUS';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';